## Travis CI Integration

language: csharp
solution: NUnitTest.sln


install:
  - nuget restore NUnitTest.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NUnitTest.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NUnitTest/bin/Release/NUnitTest.dll